# Generated by Django 4.1.5 on 2023-02-04 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='id_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.worker'),
        ),
    ]
