# Generated by Django 4.1.5 on 2023-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_answer_text_delete_skill_delete_worker_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.AddField(
            model_name='text',
            name='answers',
            field=models.ManyToManyField(to='myapp1.answer'),
        ),
    ]
